//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by JuicePlay.rc
//
#define IDCANCEL2                       3
#define IDC_BROWSE_ELEVATION            3
#define IDCANCEL3                       4
#define IDC_BROWSE_TEXTURE_COARSE       4
#define IDCANCEL4                       5
#define IDC_BROWSE_TEXTURE_DETAILED     5
#define IDD_ABOUTBOX                    100
#define ID_STATUS_DRAG                  101
#define ID_STATUS_FRAMERATE             102
#define IDD_USERPREFDLG                 103
#define IDD_OPTIONS                     105
#define IDD_Useless                     107
#define IDD_TRAINING                    107
#define IDR_MAINFRAME                   128
#define IDS_APPNAME                     129
#define IDR_FRAME_3D                    130
#define IDR_FRAME_COMPONENTS            131
#define IDR_FRAME_MOTION                132
#define IDR_FRAME_PROPERTIES            133
#define ID_MODE_DESIGN                  134
#define ID_MODE_PAUSE                   135
#define ID_MODE_CRESCENDO               136
#define ID_MODE_POSEANDSTART            137
#define ID_OPTIONS_COLORS               138
#define ID_OPTIONS_PHYSICSPARAMETERS    139
#define ID_VIEW_TOP                     140
#define ID_VIEW_FRONT                   141
#define ID_VIEW_SIDE                    142
#define ID_VIEW_CORNER                  143
#define ID_VIEW_NEWMOTIONSOURCEWINDOW   144
#define ID_EDIT_ADDMOTION               145
#define ID_EDIT_MIMICCENTERANGLEOF      146
#define IDS_NODYNAMICSDLL               146
#define ID_EDIT_MIMICAXISOF             147
#define ID_EDIT_MIMICPOSITIONOF         148
#define ID_EDIT_MIMICORIENTATIONOF      149
#define ID_DRAG_XY                      150
#define ID_DRAG_XZ                      151
#define ID_DRAG_YZ                      152
#define ID_Menu                         153
#define ID_EDIT_ADDSLIDER               154
#define ID_VIEW_NEW3DWINDOW             155
#define ID_EDIT_ADDBEAM                 156
#define ID_EDIT_ADDHINGE                159
#define ID_EDIT_DELETE                  162
#define ID_MODE_SNAP                    163
#define ID_FILE_SAVEAS                  166
#define ID_VIEW_LOOKATSELECTION         168
#define ID_Menu169                      169
#define ID_EDIT_SELECTALL               169
#define IDR_TB_MAIN                     170
#define IDR_TB_APPMODES                 171
#define IDR_TB_SPEED                    172
#define IDD_SPEEDBAR                    172
#define IDR_TB_EDITMODES                173
#define IDR_TB_VIEWS                    175
#define ID_FILE_MRU                     177
#define IDD_COLORS                      179
#define ID_EDIT_ADD_CLOCKWORK_BEHAVIOR  180
#define IDD_TERRAIN_NEW                 180
#define ID_EDIT_SYMMETRICEDITING        181
#define ID_TOOLBARS_STANDARD            182
#define ID_TOOLBARS_VIEWDIRECTIONS      183
#define ID_TOOLBARS_DESIGN              184
#define ID_TOOLBARS_EDITMODES           185
#define ID_TOOLBARS_RESTORESTANDARDLAYOUT 186
#define ID_OPTIONS_MODEL                190
#define ID_MODE_PLAY                    191
#define ID_MODE_FOLLOW                  192
#define IDD_MICRODIALOG                 193
#define ID_HELP_WEBSITE                 194
#define IDR_TB_ADD                      194
#define ID_TACK                         195
#define ID_FILE_GENERATE                196
#define ID_GENERATE_SNAKE               197
#define IDD_GENERATE_SNAKE              198
#define IDD_GENERATE_MANYPEDE           199
#define ID_GENERATE_MANYPEDE            199
#define ID_FILE_IMPORT_JPM              200
#define ID_OPTIONS_VIDEOCAPTURE         201
#define ID_EDIT_ADD_NETWORK_BEHAVIOR    202
#define ID_EDIT_ADDBALLJOINT            205
#define ID_TERRAIN_NEW                  206
#define ID_TERRAIN_SAVEAS               207
#define ID_TERRAIN_OPEN                 208
#define ID_TERRAIN_DISABLE              209
#define ID_TERRAIN_ENABLE               210
#define ID_HELP_DISCUSS                 211
#define IDD_DIALOG1                     212
#define IDD_DYNAMICSFACTORIES           213
#define ID_OPTIONS_CHOOSEDYNAMICSLIBRARY 214
#define ID_OPTIONS_GENERAL              215
#define IDD_DIALOG2                     219
#define IDD_TRAINING2                   219
#define IDC_EDIT1                       1000
#define IDC_POPULATION_SIZE             1000
#define IDC_DURATION                    1001
#define IDC_LIST1                       1003
#define IDC_COLORLIST                   1003
#define IDC_LIBRARIES                   1003
#define IDC_CAGESIZE                    1004
#define IDC_SPEED                       1006
#define IDC_SPEED_PERCENT               1007
#define IDC_CHOOSECOLOR                 1008
#define IDC_COLORSAMPLE                 1010
#define IDC_FRICTION                    1011
#define IDC_BOUNCE                      1012
#define IDC_ERP                         1013
#define IDC_CFM                         1014
#define IDC_HELPTEXT                    1015
#define IDC_MODEL_POSEDELAY             1016
#define IDC_ITERATIONS                  1016
#define IDC_MAXDELTA                    1017
#define IDC_NUMBER_CYCLES               1018
#define IDC_PHASE_DIFFERENCE            1019
#define IDC_SNAKE_HORIZONTAL            1020
#define IDC_SNAKE_VERTICAL              1021
#define IDC_SNAKE_NUMBER_SEGMENTS       1022
#define IDC_GRAVITY                     1023
#define IDC_SNAKE_PHASE_DIFFERENCE      1024
#define IDC_SNAKE_NUMBER_CYCLES         1025
#define IDC_SNAPRESOLUTION              1026
#define IDC_MODEL_SPEED                 1027
#define IDC_MINDELTA                    1028
#define IDC_ITERATIONS_ST               1029
#define IDC_TERRAIN_TEXTURE_ELEVATION   1031
#define IDC_TERRAIN_TEXTURE_BASE        1032
#define IDC_TERRAIN_TEXTURE_DETAILED    1033
#define IDC_LIST2                       1034
#define IDC_START                       1035
#define IDC_STOP                        1036
#define IDC_BUTTON1                     1037
#define IDC_NEW                         1037
#define IDC_BEHAVIOR                    1038
#define IDC_TRAIN                       1039
#define IDC_EXIT                        1039
#define IDC_Unused                      1040
#define IDC_RESTORE                     1040
#define IDC_FILENAME                    1041
#define IDC_CLOSE                       1042
#define IDC_GO                          1042
#define IDC_MODEL_POSEPHASE             1045
#define IDC_MANYPEDE_NUMBER_SEGMENTS    1046
#define IDC_TERRAIN_SCALE_HORIZONTAL    1046
#define IDC_TERRAIN_SCALE_VERTICAL      1047
#define IDC_TERRAIN_TRIANGLECOUNT       1048
#define IDC_MANYPEDE_HORIZONTAL         1049
#define IDC_MANYPEDE_VERTICAL           1050
#define IDC_STATUS                      1050
#define IDD_MODEL_FOO                   1051
#define IDD_MODEL                       1051
#define IDC_BESTSCORE                   1051
#define IDC_PREVSCORE                   1052
#define IDC_INIT_EXISTING               1054
#define IDC_INIT_RANDOM                 1055
#define IDC_CROSSOVER                   1056
#define IDC_SURVIVORS                   1057
#define IDC_MUTATIONPERCENTAGE          1058
#define IDC_MUTATIONAMOUNT              1059
#define IDC_COMBO1                      1061
#define IDC_TAB1                        1062
#define IDS_3D_INITFAILED               10000
#define ID_MODE_SYMMETRICEDITING        32785
#define ID_TB_SYMMETRIC                 32786
#define ID_TB_SNAP                      32787
#define ID_TB_VIEW_SIDE                 32788
#define ID_TB_VIEW_FRONT                32789
#define ID_TB_VIEW_TOP                  32790
#define ID_TB_VIEW_CORNER               32791
#define IDS_PROMPTSAVE_MESSAGE          32800
#define ID_ACCELERATOR32804             32804
#define ID_ACCELERATOR32806             32806
#define ID_MODE_TRAIN                   32814
#define ID_FILE_MRU_FIRES               57616
#define IDS_CAPTION_MOTIONVIEW          57666
#define IDS_CAPTION_TEXTVIEW            57667
#define IDS_CAPTION_3DVIEW              57668
#define IDS_CAPTION_PROPERTIESVIEW      57669

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        220
#define _APS_NEXT_COMMAND_VALUE         32815
#define _APS_NEXT_CONTROL_VALUE         1063
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
